import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Coffee',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Desserts',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Moktails',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
      'c7',
    ],
    title: 'Chilli garlic breadsticks',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://hebbarskitchen.com/wp-content/uploads/2020/12/chilli-garlic-breadsticks-recipe-chilli-garlic-toast-sticks-garlic-breadsticks-2-768x1152.jpeg',
    duration: 10,
    ingredients: [
      '¼ cup butter (softened)',
      '6 clove garlic (grated)',
      '2 tbsp coriander (finely chopped)',
      ' 1 tsp chilli flakes',
      '¼ tsp white pepper powder',
      '¼ tsp salt',
      '4 slice bread (white or brown)',
    ],
    steps: [
      'firstly, in a small bowl take ¼ cup butter and 6 clove garlic.',
      'add 2 tbsp coriander, 1 tsp mixed herbs, 1 tsp chilli flakes ¼ tsp white pepper powder and ¼ tsp salt.',
      'mix well making sure everything is well combined.',
      'now cut the sides of bread. i have cut only 2 sides of the bread',
      'then cut into thick strips.',
      'spread the garlic butter on the bread stirps.',
      'toast the breadsticks on pan. you can alternatively bake in oven or grill.',
      'turn over and toast until the bread turns golden brown.',
      'finally, enjoy chilli garlic breadsticks with more chilli flakes.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
      'c2',
    ],
    title: 'Dalgona Coffee',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.pexels.com/photos/4763636/pexels-photo-4763636.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: 8,
    ingredients: [
      '3 tbsp instant coffee ',
      '2 tbsp sugar',
      '400-500ml milk (we used whole milk)',
    ],
    steps: [
      'Whisk the coffee, sugar and 3 tbsp boiling water in a bowl for approximately 5 mins until the mixture is thick and fluffy with stiff peaks. ',
      'This is easiest done using an electric whisk but can be done by hand.',
      'For hot coffee, heat the milk and pour into two heatproof glasses.',
      'For cold coffee, pour the cold milk into two glasses. ',
      'Divide the coffee mixture in half and spoon evenly on top of the glasses.',
      'Serve and stir thoroughly before drinking.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c8',
    ],
    title: 'Oreo Truffles Recipe',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://bakewithshivesh.com/wp-content/uploads/2021/04/IMG_8739-scaled.jpg',
    duration: 35,
    ingredients: [
      '24 oreo cookies',
      '150 g cream cheese, softened',
      '180 g white chocolate',
    ],
    steps: [
      'In a food processor, pulse the oreos till you see fine crumbs.',
      'In a separate bowl, take cream cheese and add in the crushed oreos. Mix until well combined.',
      'Shape into 1 inch balls and refrigerate for 15-20 minutes.',
      'Melt white chocolate in the microwave/ double boiler.',
      'Dip the refrigerated truffles in the white chocolate, and allow excess chocolate to run off.',
      'Top with some more crushed oreos and allow it to set for 10 minutes.',
      'Store in an airtight container in refrigerator.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c1',
    ],
    title: 'White sauce pasta',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://images.pexels.com/photos/1487511/pexels-photo-1487511.jpeg?cs=srgb&dl=pexels-engin-akyurt-1487511.jpg&fm=jpg',
    duration: 40,
    ingredients: [
      '6 cup water',
      '1 tsp salt',
      '2 cup pasta ',
      '2 tbsp oil',
      '3 clove garlic',
      '½ onion (chopped)',
      '½ carrot (chopped)',
      '½ capsicum (chopped)',
      '3 tbsp sweet corn',
      '½ tsp pepper (crushed)',
      '½ tsp salt',
      '2 tbsp butter',
      '3 tbsp maida / plain flour',
      '2 cup milk',
      ' ½ tsp pepper (crushed)',
      '½ tsp chilli flakes',
      '½ tsp mixed herbs',
      '½ tsp salt',
      'cheese (for garnishing)',
    ],
    steps: [
      'firstly, in a large kadai boil 6 cup water and 1 tsp salt.',
      'once the water comes to a boil, add 2 cup pasta. i have used elicoidali pasta, you can alternatively use penne pasta.',
      'boil for 7 minutes, or until the pasta is cooked al dente.',
      'drain off the pasta and keep aside.',
      'in a frying pan, heat 2 tbsp oil and saute 3 clove garlic.',
      'add ½ onion, ½ carrot, ½ capsicum and 3 tbsp sweet corn.',
      'saute for a minute or until vegetables shrink slightly yet remain crunchy.',
      'further, add ½ tsp pepper and ½ tsp salt.',
      'saute well until the spices are well combined. keep aside.',
      'to prepare white sauce for pasta, heat 2 tbsp butter.',
      'add 3 tbsp maida and saute on low flame.',
      'saute until the maida turns aromatic yet do not change its colour.',
      'now add 1 cup milk and mix well.',
      'mix until the sauce thickens without forming any lumps.',
      'further, add 1 more cup of milk and continue to stir continuously.',
      'mix continuously, until the sauce thickens. if required using a whisk break the lumps.',
      'cook until the sauce turns silk smooth and creamy texture.',
      'now add ½ tsp pepper, ½ tsp chilli flakes, ½ tsp mixed herbs and ½ tsp salt.',
      'mix well making sure everything is well combined.',
      'add in sauted vegetables and combine well.',
      'now add in boiled pasta and mix gently.',
      'add 2 tbsp of boiled pasta water if the sauce thickens.',
      'mix gently making sure everything is well combined.',
      'finally, just before serving white sauce pasta, garnish with grated cheese.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c8',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c4',
      'c8',
    ],
    title: 'Indulgent Oreo Milkshake',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://bakewithshivesh.com/wp-content/uploads/2021/05/IMG_4013-scaled.jpg',
    duration: 30,
    ingredients: [
      '10 Oreos',
      '4 scoops of Ice Cream',
      '½ cup Milk',
      'Whipped Cream',
      'Cream Cheese Frosting',
      'Crushed Oreos',
      'Oreos for garnish',
    ],
    steps: [
      'In a processor, blend together the milk, Oreos, and soft vanilla ice cream.',
      'Blend for 3-4 minutes until everything comes together.',
      'In a mason jar or alternatively, in a glass, take some more cream cheese frosting and cover the glass rim with it. Stick on some crushed Oreos.',
      'Pour the milkshake into the glass.',
      'To make the whipped cream, whip the cream to stiff or heavy peaks and frost it over the Oreo milkshake! Top with some more more Oreos.',
      'Serve cold and enjoy!',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c9',
      'c10',
    ],
    title: 'Chocolate Paan Shake',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.chefkunalkapur.com/wp-content/uploads/2021/05/Chocolate-Paan-Shake-1300x867.jpg?v=1620818989',
    duration: 20,
    ingredients: [
      'Beetle Nut leaves – 8nos',
      'Gulkand (rose preserve) – 2½ tbsp',
      'Fennel Seeds – 2tsp',
      'Cardamom – 4nos',
      'Kewra water – 1tbsp',
      'Dry Coconut (desiccated) – 2tbsp',
      'Candied cherries – handful',
      'Vanilla ice cream – 2 scoops',
      'Green food colour – a pinch',
      'Milk – 750ml',
      'Chocolate sauce – 4tbsp',
    ],
    steps: [
      'To make the chocolate paan shake wash and clean the paan leaves (beetle nut leaves). ',
      'Tear the leaves into smaller bits and add it to a grinder along with gulakand, fennel seeds, cardamom, kewra water, dried coconut, candied cherries, vanilla ice cream, green food colour and milk.',
      'Blend it together to make a smooth shake. ',
      'Pour some chocolate sauce into the glass and pour the drink over it. Serve it chilled.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c9',
    ],
    title: 'Virgin Mojito Recipe',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.pexels.com/photo/clear-drinking-glass-with-sliced-lemon-4085480/',
    duration: 10,
    ingredients: [
      '30 ml club soda',
      '8 mint leaves',
      '30 ml lemon juice',
      '20 ml sugar syrup',
      'Ice cubes as required',
      '2 lemon wedges',
    ],
    steps: [
      'Take a shaker and add mint leaves, lemon wedges, sugar syrup and fresh lemon juice. ',
      'Use marble or wooden pestle to crush everything inside the shaker. ',
      'Then add 8-10 ice cubes to it.',
      'Shake well until all the ingredients release their flavours. ',
      'Then pour in a glass.',
      'Add club soda to fill up the glass and garnish with lemon wedges and mint leaves.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c4',
      'c2',
    ],
    title: 'Cappuccino Recipe',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.pexels.com/photo/close-up-of-coffee-cup-on-table-312418/',
    duration: 15,
    ingredients: [
      '2 cups milk',
      '1 cinnamon stick',
      '2 cups strong coffee',
      'Sugar - to taste',
      'Ground cinnamon',
    ],
    steps: [
      'In a saucepan heat the milk and the cinnamon stick just until milk comes to a boil.',
      'Turn heat down and let milk simmer for 10 minutes.',
      'Remove the cinnamon stick from the heated milk.',
      'Pour 1/2 cup of coffee in the cup and add sugar to taste.',
      'Now pour the hot milk, raising it high.',
      'Sprinkle ground cinnamon and serve hot.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
];
